### ISSUE TITLE
Get all farms

### ISSUE THREAD

**Issue by TehillahK** [TehillahK/pamarket-backend#3]
![Screen Shot 2021-08-26 at 4 00 58 AM](https://user-images.githubusercontent.com/56933368/130934245-32f6a2b6-2ffc-4149-9782-6a80d8918a43.png)
![Simulator Screen Shot - iPhone 11 - 2021-08-26 at 04 13 40](https://user-images.githubusercontent.com/56933368/130937115-00d5b043-2c68-426d-a68c-31bc54417461.png)

**Comment by TehillahK** [comment]
all farms will return an array  of that json object.

**Comment by Kronik946** [comment]
server app will be uploaded on close of the last issue as it will incorporate all amendments
