### ISSUE TITLE
get farmCrops(farm id)

### ISSUE THREAD

**Issue by TehillahK** [TehillahK/pamarket-backend#4]
![Screen Shot 2021-08-26 at 4 14 18 AM](https://user-images.githubusercontent.com/56933368/130936291-e65c87da-b2bf-483e-b457-0470ba412307.png)
![Simulator Screen Shot - iPhone 11 - 2021-08-26 at 04 13 49](https://user-images.githubusercontent.com/56933368/130937604-eee52c2f-1280-415a-8bdb-fadc41e394af.png)
![Simulator Screen Shot - iPhone 11 - 2021-08-26 at 04 13 54](https://user-images.githubusercontent.com/56933368/130937613-9fa89154-e692-4052-8e94-ab2f9c5727e2.png)

**Comment by TehillahK** [comment]
shuld return all  crops associated to a farm

**Comment by Kronik946** [comment]
server app will be uploaded on close of the last issue as it will incorporate all amendments
